{
    "pipe-parallel-size": 1,
    "model-parallel-size": 1,
    "num-layers": 24,
    "hidden-size": 2048,
    "num-attention-heads": 16,
    "seq-length": 4096,
    "max-position-embeddings": 4096,
    "norm": "layernorm",
    "pos-emb": "rotary",
    "rotary_pct": 0.25,
    "activation": "gelu",
    "no-weight-tying": true,
    "gpt-j-residual": true,
    "output-layer-parallelism": "column",
    "init_method": "small_init",
    "output_layer_init_method": "wang_init",
    "scaled-upper-triang-masked-softmax-fusion": true,
    "bias-gelu-fusion": true,
    "attention-config": [
        [
            [
                "flash"
            ],
            24
        ]
    ],
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.00012,
            "betas": [
                0.9,
                0.95
            ],
            "eps": 1.0e-8
        }
    },
    "min_lr": 1.2e-5,
    "zero_optimization": {
        "stage": 1,
        "allgather_partitions": true,
        "allgather_bucket_size": 1260000000,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 1260000000,
        "contiguous_gradients": true,
        "cpu_offload": false
    },
    "train_micro_batch_size_per_gpu": 4,
    "gradient_accumulation_steps": 4,
    "eval_batch_size": 4,
    "data-impl": "mmap",
    "checkpoint-activations": true,
    "checkpoint-num-layers": 1,
    "partition-activations": true,
    "synchronize-each-layer": true,
    "gradient_clipping": 1.0,
    "weight-decay": 0.1,
    "hidden-dropout": 0,
    "attention-dropout": 0,
    "fp16": {
        "fp16": true,
        "enabled": true,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 12,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "train-iters": 180000,
    "lr-decay-iters": 180000,
    "distributed-backend": "nccl",
    "lr-decay-style": "cosine",
    "warmup": 0.01,
    "checkpoint-factor": 1000,
    "eval-interval": 1001,
    "eval-iters": 10,
    "eval_tasks": [
        "jcommonsenseqa"
    ],
    "use_wandb": true,
    "wandb_host": "https://stability.wandb.io",
    "wandb_team": "stability-llm",
    "wandb_project": "stable-lm-jp",
    "wandb_group": "1B",
    "wandb_name": "1B.nai.mc4_cc100_wiki_redpajama.bs_4m.tp_1.dtype_int64",
    "save": "/fsx/jp-llm/ckpts/1b_tok=nai_data=mc4-cc100-wiki-redpajama_bs=4m_tp=1_pp=1_init=wang-small-init_dtype=int64",
    "load": "/fsx/jp-llm/ckpts/1b_tok=nai_data=mc4-cc100-wiki-redpajama_bs=4m_tp=1_pp=1_init=wang-small-init_dtype=int64",
    "tokenizer-type": "SPMTokenizer",
    "vocab-file": "/fsx/jp-llm/novelai.model",
    "log-interval": 10,
    "steps_per_print": 10,
    "wall_clock_breakdown": true,
    "train-data-paths": [
        "/fsx/jp-llm/merged/mc4/mc4_text_document",
        "/fsx/jp-llm/merged/cc-100/cc-100_text_document",
        "/fsx/jp-llm/merged/wikipedia/wikipedia_text_document",
        "/fsx/jp-llm/merged/redpajama/stackexchange/stackexchange_text_document",
        "/fsx/jp-llm/merged/redpajama/arxiv/arxiv_text_document",
        "/fsx/jp-llm/merged/redpajama/wiki/wiki_text_document",
        "/fsx/jp-llm/merged/redpajama/books/books_text_document",
        "/fsx/jp-llm/merged/redpajama/github/github_text_document",
        "/fsx/jp-llm/merged/redpajama/c4/c4_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2023/tokenized_1_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2023/tokenized_0_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2023/tokenized_2_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2023/tokenized_3_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2020/tokenized_3_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2020/tokenized_2_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2020/tokenized_0_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2020/tokenized_1_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2022/tokenized_3_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2022/tokenized_2_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2022/tokenized_0_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2022/tokenized_1_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2021/tokenized_2_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2021/tokenized_3_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2021/tokenized_1_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2021/tokenized_0_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2019/tokenized_2_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2019/tokenized_3_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2019/tokenized_1_text_document",
        "/fsx/jp-llm/merged/redpajama/common-crawl-by-year/2019/tokenized_0_text_document"
    ],
    "train-data-weights": [
        74.77,
        23.43,
        1.8,
        2.0,
        2.5,
        4.5,
        4.5,
        4.5,
        15.0,
        3.86,
        4.48,
        3.08,
        2.95,
        2.88,
        3.05,
        4.77,
        3.66,
        2.49,
        2.74,
        4.0,
        3.33,
        3.26,
        3.18,
        3.56,
        3.82,
        2.54,
        2.3,
        3.12,
        3.93
    ],
    "valid-data-paths": [
        "/fsx/jp-llm/merged/mc4/mc4_text_document",
        "/fsx/jp-llm/merged/cc-100/cc-100_text_document",
        "/fsx/jp-llm/merged/wikipedia/wikipedia_text_document"
    ],
    "valid-data-weights": [
        74.77,
        23.43,
        1.8
    ],
    "test-data-paths": [
        "/fsx/jp-llm/merged/mc4/mc4_text_document",
        "/fsx/jp-llm/merged/cc-100/cc-100_text_document",
        "/fsx/jp-llm/merged/wikipedia/wikipedia_text_document"
    ],
    "test-data-weights": [
        74.77,
        23.43,
        1.8
    ],
    "launcher": "slurm",
    "deepspeed_slurm": true
}